version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes: 
      - mysql_data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:
